# Generated by Django 4.0.5 on 2022-06-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flydate',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
